### ISSUE TITLE
don't loads(

### ISSUE THREAD

**Issue by brothermechanic** [Soft8Soft/verge3d-blender-addon#1]
![screenshot_20180816_193048](https://user-images.githubusercontent.com/3109995/44221734-e29b3900-a171-11e8-8aa1-9f192c76dca6.jpg)
```
Traceback (most recent call last):
  File "/usr/share/blender/2.79/scripts/modules/addon_utils.py", line 370, in enable
    mod.register()
  File "/home/bm/.config/blender/2.79/scripts/addons/verge3d-blender-addon-master/__init__.py", line 339, in register
    from . import custom_props, custom_ui, profile
  File "/home/bm/.config/blender/2.79/scripts/addons/verge3d-blender-addon-master/custom_ui.py", line 23, in <module>
    import verge3d
ModuleNotFoundError: No module named 'verge3d'


```

**Comment by alexkowel** [comment]
Hi!

It happens because your destination directory is "verge3d-blender-addon-master", not just "verge3d". Mentioned this in updated installation instructions.

Thanks for reporting!
